version: '3.7'
services:
  api:
    build:
      context: ./go-grpc-api-gateway
    ports:
      - 3000:3000
  auth:
    build:
      context: ./go-grpc-auth-svc
  product:
    build:
      context: ./go-grpc-product-svc
  echo:
    build:
      context: ./go-grpc-echo-svc
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
volumes:
  db_data:
